# Generated by Django 3.2.9 on 2021-12-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idafarmuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.CharField(max_length=255, null=True)),
                ('servicecode', models.CharField(max_length=255, null=True)),
                ('phooneNumber', models.CharField(max_length=225)),
                ('level', models.CharField(max_length=225)),
                ('category', models.CharField(max_length=225)),
                ('sizeofland', models.CharField(max_length=225)),
                ('names', models.CharField(max_length=225)),
                ('idnumber', models.CharField(max_length=225)),
                ('created_on', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
